#LeeesBungeeQueue Configuration V1.0.0
#make sure the queue server is called queue in the bungee config
#and then make the main server the default one you login to
#and then it should work if it doesnt add me on discord for help
#http://discord.6b6t.org join for help there will be an error because
#i havent fully gotten the priority to work for now it has no priority stuff enabled
#but the error for super slots is nothing to worry about i works fine

#Position in queue message shows above the hotbar
CURRENT_LIMBO_POSITION: "&6Position in queue: &l<position>"

#Server is full message when player joins the queue
SEND_TO_LIMBO: "&66b6t is full"

#Connecting to server message
LEFT_LIMBO_JOIN_SERVER: "&6Connecting to <server>"

#Max players allowed onto main server
GLOBAL_SLOTS: 100
